import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Cemento Portland",
    description: "Cemento de alta calidad para construcción general",
    base_price: 8500.00,
    wholesale_price: 8000.00,
    stock: 100,
    min_stock: 10,
    sku: "CEM-001",
    barcode: "7791234567890",
    category: "Cementos",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Ladrillos Comunes",
    description: "Ladrillos comunes de 12x18x33 cm",
    base_price: 450.00,
    wholesale_price: 400.00,
    stock: 500,
    min_stock: 50,
    sku: "LAD-001",
    barcode: "7791234567891",
    category: "Ladrillos",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Arena Fina",
    description: "Arena fina para mezclas y revoques",
    base_price: 3500.00,
    stock: 200,
    min_stock: 20,
    sku: "ARE-001",
    barcode: "7791234567892",
    category: "Áridos",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Piedra Partida",
    description: "Piedra partida 6-20 para hormigón",
    base_price: 4200.00,
    wholesale_price: 3800.00,
    stock: 150,
    min_stock: 15,
    sku: "PIE-001",
    barcode: "7791234567893",
    category: "Áridos",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Hierro del 8",
    description: "Hierro redondo de 8mm para estructuras",
    base_price: 12000.00,
    wholesale_price: 11000.00,
    stock: 80,
    min_stock: 10,
    sku: "HIE-008",
    barcode: "7791234567894",
    category: "Hierros",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Hierro del 10",
    description: "Hierro redondo de 10mm para estructuras",
    base_price: 15000.00,
    wholesale_price: 14000.00,
    stock: 60,
    min_stock: 8,
    sku: "HIE-010",
    barcode: "7791234567895",
    category: "Hierros",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Cal Hidratada",
    description: "Cal hidratada para revoques y pinturas",
    base_price: 2800.00,
    wholesale_price: 2500.00,
    stock: 120,
    min_stock: 12,
    sku: "CAL-001",
    barcode: "7791234567896",
    category: "Cementos",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Yeso Común",
    description: "Yeso común para revoques interiores",
    base_price: 3200.00,
    wholesale_price: 2900.00,
    stock: 90,
    min_stock: 9,
    sku: "YES-001",
    barcode: "7791234567897",
    category: "Revoques",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Malla Sima",
    description: "Malla sima para revoques, rollo de 50m",
    base_price: 8500.00,
    wholesale_price: 8000.00,
    stock: 40,
    min_stock: 5,
    sku: "MAL-001",
    barcode: "7791234567898",
    category: "Revoques",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Tubos PVC 110mm",
    description: "Tubos de PVC de 110mm para desagües",
    base_price: 4500.00,
    wholesale_price: 4200.00,
    stock: 70,
    min_stock: 7,
    sku: "PVC-110",
    barcode: "7791234567899",
    category: "Plomería",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Cable Eléctrico 2.5mm",
    description: "Cable eléctrico de 2.5mm², rollo 100m",
    base_price: 25000.00,
    wholesale_price: 23000.00,
    stock: 30,
    min_stock: 5,
    sku: "CAB-2.5",
    barcode: "7791234567900",
    category: "Electricidad",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Pintura Látex",
    description: "Pintura látex blanca, balde 20L",
    base_price: 15000.00,
    wholesale_price: 14000.00,
    stock: 50,
    min_stock: 5,
    sku: "PIN-LAT",
    barcode: "7791234567901",
    category: "Pinturas",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

